@base_url = http://localhost:8080/api/chat

POST {{base_url}}
Content-Type: application/json

{
  "message": "What services do you provide"
}
###

# Testing Ollama directly

POST http://localhost:11434/api/generate
Content-Type: application/json

{
  "model": "llama3",
  "prompt": "Say hello",
  "stream": false
}